// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comment.proto

package comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Comment struct {
	CommenterId          int32    `protobuf:"varint,1,opt,name=commenterId,proto3" json:"commenterId,omitempty"`
	CommentId            int32    `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	CommentText          string   `protobuf:"bytes,3,opt,name=commentText,proto3" json:"commentText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{0}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetCommenterId() int32 {
	if m != nil {
		return m.CommenterId
	}
	return 0
}

func (m *Comment) GetCommentId() int32 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *Comment) GetCommentText() string {
	if m != nil {
		return m.CommentText
	}
	return ""
}

type CreateCommentRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	CommentText          string   `protobuf:"bytes,3,opt,name=commentText,proto3" json:"commentText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentRequest) Reset()         { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()    {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{1}
}

func (m *CreateCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentRequest.Unmarshal(m, b)
}
func (m *CreateCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentRequest.Marshal(b, m, deterministic)
}
func (m *CreateCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentRequest.Merge(m, src)
}
func (m *CreateCommentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCommentRequest.Size(m)
}
func (m *CreateCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentRequest proto.InternalMessageInfo

func (m *CreateCommentRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateCommentRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreateCommentRequest) GetCommentText() string {
	if m != nil {
		return m.CommentText
	}
	return ""
}

type CreateCommentResponse struct {
	CommentId            int32    `protobuf:"varint,1,opt,name=commentId,proto3" json:"commentId,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCommentResponse) Reset()         { *m = CreateCommentResponse{} }
func (m *CreateCommentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCommentResponse) ProtoMessage()    {}
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{2}
}

func (m *CreateCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCommentResponse.Unmarshal(m, b)
}
func (m *CreateCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCommentResponse.Marshal(b, m, deterministic)
}
func (m *CreateCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCommentResponse.Merge(m, src)
}
func (m *CreateCommentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCommentResponse.Size(m)
}
func (m *CreateCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCommentResponse proto.InternalMessageInfo

func (m *CreateCommentResponse) GetCommentId() int32 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

func (m *CreateCommentResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GetAllPostCommentsRequest struct {
	PostId               int32    `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPostCommentsRequest) Reset()         { *m = GetAllPostCommentsRequest{} }
func (m *GetAllPostCommentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPostCommentsRequest) ProtoMessage()    {}
func (*GetAllPostCommentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{3}
}

func (m *GetAllPostCommentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPostCommentsRequest.Unmarshal(m, b)
}
func (m *GetAllPostCommentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPostCommentsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPostCommentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPostCommentsRequest.Merge(m, src)
}
func (m *GetAllPostCommentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPostCommentsRequest.Size(m)
}
func (m *GetAllPostCommentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPostCommentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPostCommentsRequest proto.InternalMessageInfo

func (m *GetAllPostCommentsRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type GetAllPostCommentsResponse struct {
	Comments             []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Body                 string     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllPostCommentsResponse) Reset()         { *m = GetAllPostCommentsResponse{} }
func (m *GetAllPostCommentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPostCommentsResponse) ProtoMessage()    {}
func (*GetAllPostCommentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{4}
}

func (m *GetAllPostCommentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPostCommentsResponse.Unmarshal(m, b)
}
func (m *GetAllPostCommentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPostCommentsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPostCommentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPostCommentsResponse.Merge(m, src)
}
func (m *GetAllPostCommentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPostCommentsResponse.Size(m)
}
func (m *GetAllPostCommentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPostCommentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPostCommentsResponse proto.InternalMessageInfo

func (m *GetAllPostCommentsResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *GetAllPostCommentsResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type LikeCommentRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CommentId            int32    `protobuf:"varint,2,opt,name=commentId,proto3" json:"commentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentRequest) Reset()         { *m = LikeCommentRequest{} }
func (m *LikeCommentRequest) String() string { return proto.CompactTextString(m) }
func (*LikeCommentRequest) ProtoMessage()    {}
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{5}
}

func (m *LikeCommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentRequest.Unmarshal(m, b)
}
func (m *LikeCommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentRequest.Marshal(b, m, deterministic)
}
func (m *LikeCommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentRequest.Merge(m, src)
}
func (m *LikeCommentRequest) XXX_Size() int {
	return xxx_messageInfo_LikeCommentRequest.Size(m)
}
func (m *LikeCommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentRequest proto.InternalMessageInfo

func (m *LikeCommentRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LikeCommentRequest) GetCommentId() int32 {
	if m != nil {
		return m.CommentId
	}
	return 0
}

type LikeCommentResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeCommentResponse) Reset()         { *m = LikeCommentResponse{} }
func (m *LikeCommentResponse) String() string { return proto.CompactTextString(m) }
func (*LikeCommentResponse) ProtoMessage()    {}
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749aee09ea917828, []int{6}
}

func (m *LikeCommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeCommentResponse.Unmarshal(m, b)
}
func (m *LikeCommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeCommentResponse.Marshal(b, m, deterministic)
}
func (m *LikeCommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeCommentResponse.Merge(m, src)
}
func (m *LikeCommentResponse) XXX_Size() int {
	return xxx_messageInfo_LikeCommentResponse.Size(m)
}
func (m *LikeCommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeCommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikeCommentResponse proto.InternalMessageInfo

func (m *LikeCommentResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Comment)(nil), "comment.Comment")
	proto.RegisterType((*CreateCommentRequest)(nil), "comment.CreateCommentRequest")
	proto.RegisterType((*CreateCommentResponse)(nil), "comment.CreateCommentResponse")
	proto.RegisterType((*GetAllPostCommentsRequest)(nil), "comment.GetAllPostCommentsRequest")
	proto.RegisterType((*GetAllPostCommentsResponse)(nil), "comment.GetAllPostCommentsResponse")
	proto.RegisterType((*LikeCommentRequest)(nil), "comment.LikeCommentRequest")
	proto.RegisterType((*LikeCommentResponse)(nil), "comment.LikeCommentResponse")
}

func init() {
	proto.RegisterFile("comment.proto", fileDescriptor_749aee09ea917828)
}

var fileDescriptor_749aee09ea917828 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4d, 0x4f, 0xf2, 0x40,
	0x10, 0xc7, 0x9f, 0x85, 0x47, 0xb0, 0xd3, 0x60, 0xcc, 0xf8, 0x92, 0x5a, 0xd1, 0x34, 0xeb, 0xa5,
	0x26, 0x86, 0x03, 0x7c, 0x02, 0xc3, 0xc1, 0x94, 0x78, 0x20, 0xd5, 0xb3, 0x46, 0xe8, 0x26, 0x12,
	0x5e, 0xb6, 0x76, 0x17, 0xa3, 0x9f, 0xc2, 0xaf, 0x6c, 0x2c, 0xd3, 0x76, 0x0b, 0x85, 0x70, 0xdb,
	0x79, 0xfd, 0xfd, 0x67, 0x26, 0x0b, 0xad, 0xb1, 0x9c, 0xcf, 0xc5, 0x42, 0x77, 0xe2, 0x44, 0x6a,
	0x89, 0x4d, 0x32, 0xf9, 0x14, 0x9a, 0xfd, 0xd5, 0x13, 0x3d, 0xb0, 0xc9, 0x2b, 0x92, 0x20, 0x72,
	0x98, 0xc7, 0xfc, 0x83, 0xd0, 0x74, 0x61, 0x1b, 0x2c, 0x32, 0x83, 0xc8, 0xa9, 0xa5, 0xf1, 0xc2,
	0x61, 0xd4, 0x3f, 0x8b, 0x2f, 0xed, 0xd4, 0x3d, 0xe6, 0x5b, 0xa1, 0xe9, 0xe2, 0xef, 0x70, 0xda,
	0x4f, 0xc4, 0x9b, 0x16, 0x84, 0x0c, 0xc5, 0xc7, 0x52, 0x28, 0x8d, 0xe7, 0xd0, 0x58, 0x2a, 0x03,
	0x4a, 0xd6, 0x9f, 0x3f, 0x96, 0xaa, 0x80, 0x91, 0xb5, 0x07, 0x29, 0x80, 0xb3, 0x35, 0x92, 0x8a,
	0xe5, 0x42, 0x89, 0xf2, 0x08, 0x6c, 0x7d, 0x04, 0x84, 0xff, 0x23, 0x19, 0x7d, 0xa7, 0x38, 0x2b,
	0x4c, 0xdf, 0xbc, 0x07, 0x17, 0x0f, 0x42, 0xdf, 0xcf, 0x66, 0x43, 0xa9, 0x34, 0xb5, 0x53, 0x86,
	0x72, 0x52, 0xc8, 0x4c, 0x85, 0xfc, 0x05, 0xdc, 0xaa, 0x22, 0x12, 0x71, 0x07, 0x87, 0xc4, 0x54,
	0x0e, 0xf3, 0xea, 0xbe, 0xdd, 0x3d, 0xee, 0x64, 0xf7, 0xc9, 0x04, 0xe7, 0x19, 0x95, 0xa2, 0x06,
	0x80, 0x8f, 0x93, 0xe9, 0xbe, 0x7b, 0xdc, 0x79, 0x37, 0x7e, 0x0b, 0x27, 0xa5, 0x5e, 0x24, 0x32,
	0xc3, 0xb2, 0x02, 0xdb, 0xfd, 0xa9, 0xc1, 0x11, 0xe5, 0x3d, 0x89, 0xe4, 0x73, 0x32, 0x16, 0x38,
	0x84, 0x56, 0x69, 0xd3, 0x78, 0x55, 0x8c, 0x52, 0x71, 0x6b, 0xf7, 0x7a, 0x5b, 0x78, 0x85, 0xe5,
	0xff, 0xf0, 0x15, 0x70, 0x73, 0x77, 0xc8, 0xf3, 0xba, 0xad, 0xd7, 0x70, 0x6f, 0x76, 0xe6, 0xe4,
	0x80, 0x01, 0xd8, 0xc6, 0xc0, 0x78, 0x99, 0x57, 0x6d, 0xae, 0xd4, 0x6d, 0x57, 0x07, 0xb3, 0x5e,
	0xa3, 0x46, 0xfa, 0x9f, 0x7a, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x15, 0x2b, 0xf5, 0x60,
	0x03, 0x00, 0x00,
}
