// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	PosterId             int32    `protobuf:"varint,1,opt,name=posterId,proto3" json:"posterId,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	PostText             string   `protobuf:"bytes,3,opt,name=postText,proto3" json:"postText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetPosterId() int32 {
	if m != nil {
		return m.PosterId
	}
	return 0
}

func (m *Post) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *Post) GetPostText() string {
	if m != nil {
		return m.PostText
	}
	return ""
}

type CreatePostRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostText             string   `protobuf:"bytes,2,opt,name=postText,proto3" json:"postText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePostRequest) GetPostText() string {
	if m != nil {
		return m.PostText
	}
	return ""
}

type CreatePostResponse struct {
	PostId               int32    `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreatePostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GetPostFeedRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostFeedRequest) Reset()         { *m = GetPostFeedRequest{} }
func (m *GetPostFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostFeedRequest) ProtoMessage()    {}
func (*GetPostFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *GetPostFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostFeedRequest.Unmarshal(m, b)
}
func (m *GetPostFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetPostFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostFeedRequest.Merge(m, src)
}
func (m *GetPostFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostFeedRequest.Size(m)
}
func (m *GetPostFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostFeedRequest proto.InternalMessageInfo

func (m *GetPostFeedRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetPostFeedResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostFeedResponse) Reset()         { *m = GetPostFeedResponse{} }
func (m *GetPostFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostFeedResponse) ProtoMessage()    {}
func (*GetPostFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *GetPostFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostFeedResponse.Unmarshal(m, b)
}
func (m *GetPostFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostFeedResponse.Marshal(b, m, deterministic)
}
func (m *GetPostFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostFeedResponse.Merge(m, src)
}
func (m *GetPostFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostFeedResponse.Size(m)
}
func (m *GetPostFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostFeedResponse proto.InternalMessageInfo

func (m *GetPostFeedResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetPostFeedResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type LikePostRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId               int32    `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostRequest) Reset()         { *m = LikePostRequest{} }
func (m *LikePostRequest) String() string { return proto.CompactTextString(m) }
func (*LikePostRequest) ProtoMessage()    {}
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *LikePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostRequest.Unmarshal(m, b)
}
func (m *LikePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostRequest.Marshal(b, m, deterministic)
}
func (m *LikePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostRequest.Merge(m, src)
}
func (m *LikePostRequest) XXX_Size() int {
	return xxx_messageInfo_LikePostRequest.Size(m)
}
func (m *LikePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostRequest proto.InternalMessageInfo

func (m *LikePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LikePostRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type LikePostResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostResponse) Reset()         { *m = LikePostResponse{} }
func (m *LikePostResponse) String() string { return proto.CompactTextString(m) }
func (*LikePostResponse) ProtoMessage()    {}
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *LikePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostResponse.Unmarshal(m, b)
}
func (m *LikePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostResponse.Marshal(b, m, deterministic)
}
func (m *LikePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostResponse.Merge(m, src)
}
func (m *LikePostResponse) XXX_Size() int {
	return xxx_messageInfo_LikePostResponse.Size(m)
}
func (m *LikePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostResponse proto.InternalMessageInfo

func (m *LikePostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "post.Post")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "post.CreatePostResponse")
	proto.RegisterType((*GetPostFeedRequest)(nil), "post.GetPostFeedRequest")
	proto.RegisterType((*GetPostFeedResponse)(nil), "post.GetPostFeedResponse")
	proto.RegisterType((*LikePostRequest)(nil), "post.LikePostRequest")
	proto.RegisterType((*LikePostResponse)(nil), "post.LikePostResponse")
}

func init() {
	proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1)
}

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x6d, 0x5a, 0x95, 0xcb, 0x00, 0x1c, 0xa2, 0x98, 0x4c, 0x91, 0x07, 0x94, 0x01, 0x75,
	0x28, 0x23, 0x0b, 0x15, 0x88, 0xaa, 0x82, 0x01, 0x05, 0xc4, 0x4e, 0xc9, 0x0d, 0x15, 0x12, 0x0e,
	0xb1, 0x8b, 0xe0, 0x77, 0xf2, 0x87, 0x90, 0x1d, 0xe7, 0x3b, 0x08, 0xb6, 0x7b, 0xb9, 0x77, 0xef,
	0xbd, 0xbc, 0x04, 0x20, 0x95, 0x4a, 0xcf, 0xd2, 0x4c, 0x6a, 0x89, 0x9e, 0x99, 0xc5, 0x13, 0x78,
	0xf7, 0x52, 0x69, 0x0c, 0x60, 0x62, 0x30, 0x65, 0xab, 0x84, 0xb3, 0x90, 0x45, 0xa3, 0xb8, 0xc4,
	0x38, 0x85, 0xb1, 0x99, 0x57, 0x09, 0x1f, 0xd8, 0x8d, 0x43, 0xc5, 0xcd, 0x23, 0x7d, 0x6a, 0x3e,
	0x0c, 0x59, 0xb4, 0x1b, 0x97, 0x58, 0x2c, 0xe1, 0xe0, 0x2a, 0xa3, 0x67, 0x4d, 0x46, 0x3d, 0xa6,
	0xf7, 0x2d, 0x29, 0x6d, 0x84, 0xb6, 0xaa, 0x66, 0xe1, 0x50, 0x43, 0x68, 0xd0, 0x12, 0xba, 0x04,
	0xac, 0x0b, 0xa9, 0x54, 0xbe, 0x29, 0xaa, 0x45, 0x62, 0x8d, 0x48, 0x08, 0xde, 0x5a, 0x26, 0x5f,
	0x4e, 0xc5, 0xce, 0xe2, 0x0c, 0x70, 0x49, 0xda, 0x9c, 0xdf, 0x10, 0x25, 0x7f, 0x64, 0x11, 0xb7,
	0x70, 0xd8, 0x60, 0x3b, 0xc3, 0x10, 0x46, 0xc6, 0x42, 0x71, 0x16, 0x0e, 0x23, 0x7f, 0x0e, 0x33,
	0xdb, 0xa4, 0xcd, 0x94, 0x2f, 0x7a, 0xad, 0x17, 0xb0, 0x77, 0xb7, 0x79, 0xfd, 0x57, 0x07, 0xbf,
	0x94, 0x2c, 0x4e, 0x61, 0xbf, 0x92, 0x70, 0x61, 0x0a, 0x2b, 0x56, 0x59, 0xcd, 0xbf, 0x19, 0xf8,
	0x86, 0xf4, 0x40, 0xd9, 0xc7, 0xe6, 0x85, 0x70, 0x01, 0x50, 0xf5, 0x86, 0xc7, 0x79, 0xde, 0xce,
	0x27, 0x09, 0x78, 0x77, 0x91, 0x9b, 0x88, 0x1d, 0xbc, 0x06, 0xbf, 0x56, 0x05, 0x3a, 0x6a, 0xb7,
	0xcb, 0xe0, 0xa4, 0x67, 0x53, 0xaa, 0x5c, 0xc0, 0xa4, 0x78, 0x01, 0x3c, 0xca, 0x89, 0xad, 0x4e,
	0x82, 0x69, 0xfb, 0x71, 0x71, 0xbc, 0x1e, 0xdb, 0x7f, 0xf5, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x72, 0x32, 0x5f, 0xf1, 0xb9, 0x02, 0x00, 0x00,
}
