// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostType struct {
	PosterId             int32    `protobuf:"varint,1,opt,name=posterId,proto3" json:"posterId,omitempty"`
	PostId               string   `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	PostText             string   `protobuf:"bytes,3,opt,name=postText,proto3" json:"postText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostType) Reset()         { *m = PostType{} }
func (m *PostType) String() string { return proto.CompactTextString(m) }
func (*PostType) ProtoMessage()    {}
func (*PostType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{0}
}

func (m *PostType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostType.Unmarshal(m, b)
}
func (m *PostType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostType.Marshal(b, m, deterministic)
}
func (m *PostType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostType.Merge(m, src)
}
func (m *PostType) XXX_Size() int {
	return xxx_messageInfo_PostType.Size(m)
}
func (m *PostType) XXX_DiscardUnknown() {
	xxx_messageInfo_PostType.DiscardUnknown(m)
}

var xxx_messageInfo_PostType proto.InternalMessageInfo

func (m *PostType) GetPosterId() int32 {
	if m != nil {
		return m.PosterId
	}
	return 0
}

func (m *PostType) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostType) GetPostText() string {
	if m != nil {
		return m.PostText
	}
	return ""
}

type CreatePostRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostText             string   `protobuf:"bytes,2,opt,name=postText,proto3" json:"postText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{1}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePostRequest) GetPostText() string {
	if m != nil {
		return m.PostText
	}
	return ""
}

type CreatePostResponse struct {
	PostId               string   `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GetPostFeedRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostFeedRequest) Reset()         { *m = GetPostFeedRequest{} }
func (m *GetPostFeedRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostFeedRequest) ProtoMessage()    {}
func (*GetPostFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{3}
}

func (m *GetPostFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostFeedRequest.Unmarshal(m, b)
}
func (m *GetPostFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostFeedRequest.Marshal(b, m, deterministic)
}
func (m *GetPostFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostFeedRequest.Merge(m, src)
}
func (m *GetPostFeedRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostFeedRequest.Size(m)
}
func (m *GetPostFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostFeedRequest proto.InternalMessageInfo

func (m *GetPostFeedRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetPostFeedResponse struct {
	Posts                []*PostType `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Body                 string      `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPostFeedResponse) Reset()         { *m = GetPostFeedResponse{} }
func (m *GetPostFeedResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostFeedResponse) ProtoMessage()    {}
func (*GetPostFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{4}
}

func (m *GetPostFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostFeedResponse.Unmarshal(m, b)
}
func (m *GetPostFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostFeedResponse.Marshal(b, m, deterministic)
}
func (m *GetPostFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostFeedResponse.Merge(m, src)
}
func (m *GetPostFeedResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostFeedResponse.Size(m)
}
func (m *GetPostFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostFeedResponse proto.InternalMessageInfo

func (m *GetPostFeedResponse) GetPosts() []*PostType {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *GetPostFeedResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type LikePostRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PostId               string   `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostRequest) Reset()         { *m = LikePostRequest{} }
func (m *LikePostRequest) String() string { return proto.CompactTextString(m) }
func (*LikePostRequest) ProtoMessage()    {}
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{5}
}

func (m *LikePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostRequest.Unmarshal(m, b)
}
func (m *LikePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostRequest.Marshal(b, m, deterministic)
}
func (m *LikePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostRequest.Merge(m, src)
}
func (m *LikePostRequest) XXX_Size() int {
	return xxx_messageInfo_LikePostRequest.Size(m)
}
func (m *LikePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostRequest proto.InternalMessageInfo

func (m *LikePostRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LikePostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type LikePostResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostResponse) Reset()         { *m = LikePostResponse{} }
func (m *LikePostResponse) String() string { return proto.CompactTextString(m) }
func (*LikePostResponse) ProtoMessage()    {}
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{6}
}

func (m *LikePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostResponse.Unmarshal(m, b)
}
func (m *LikePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostResponse.Marshal(b, m, deterministic)
}
func (m *LikePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostResponse.Merge(m, src)
}
func (m *LikePostResponse) XXX_Size() int {
	return xxx_messageInfo_LikePostResponse.Size(m)
}
func (m *LikePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostResponse proto.InternalMessageInfo

func (m *LikePostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*PostType)(nil), "post.PostType")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "post.CreatePostResponse")
	proto.RegisterType((*GetPostFeedRequest)(nil), "post.GetPostFeedRequest")
	proto.RegisterType((*GetPostFeedResponse)(nil), "post.GetPostFeedResponse")
	proto.RegisterType((*LikePostRequest)(nil), "post.LikePostRequest")
	proto.RegisterType((*LikePostResponse)(nil), "post.LikePostResponse")
}

func init() {
	proto.RegisterFile("proto/post.proto", fileDescriptor_5e57bba97c118b83)
}

var fileDescriptor_5e57bba97c118b83 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0xfb, 0x45, 0x9c, 0x80, 0xd6, 0x11, 0x6b, 0xcc, 0x29, 0x2c, 0x22, 0x39, 0x48, 0x85,
	0x7a, 0xf4, 0x62, 0x51, 0x2c, 0x05, 0x41, 0x89, 0x3d, 0x79, 0xb3, 0x66, 0x0e, 0x45, 0x70, 0x63,
	0x76, 0x2b, 0xf6, 0x77, 0xfa, 0x87, 0x64, 0x93, 0xdd, 0x7c, 0x56, 0xf4, 0x36, 0x1f, 0x6f, 0xde,
	0x7b, 0x79, 0x59, 0x18, 0x26, 0xa9, 0x50, 0xe2, 0x22, 0x11, 0x52, 0x8d, 0xb3, 0x12, 0x7b, 0xba,
	0xe6, 0xcf, 0xe0, 0x3c, 0x0a, 0xa9, 0x16, 0x9b, 0x84, 0xd0, 0x07, 0x47, 0xcf, 0x28, 0x9d, 0xc7,
	0x1e, 0x0b, 0x58, 0xd8, 0x8f, 0x8a, 0x1e, 0x47, 0x30, 0xd0, 0xf5, 0x3c, 0xf6, 0x3a, 0x01, 0x0b,
	0x77, 0x23, 0xd3, 0xd9, 0x9b, 0x05, 0x7d, 0x29, 0xaf, 0x9b, 0x6d, 0x8a, 0x9e, 0xcf, 0xe0, 0xe0,
	0x26, 0xa5, 0x17, 0x45, 0x5a, 0x21, 0xa2, 0x8f, 0x35, 0x49, 0xa5, 0x89, 0xd6, 0xb2, 0x22, 0x61,
	0xba, 0x1a, 0x51, 0xa7, 0x41, 0x74, 0x0d, 0x58, 0x25, 0x92, 0x89, 0x78, 0x97, 0x54, 0xb1, 0xc4,
	0x6a, 0x96, 0x10, 0x7a, 0x4b, 0x11, 0x6f, 0x0c, 0x4b, 0x56, 0xf3, 0x73, 0xc0, 0x19, 0x29, 0x7d,
	0x7e, 0x47, 0x14, 0xff, 0xe1, 0x85, 0x3f, 0xc0, 0x61, 0x0d, 0x6d, 0x04, 0x4f, 0xa1, 0xaf, 0x25,
	0xa4, 0xc7, 0x82, 0x6e, 0xe8, 0x4e, 0xf6, 0xc6, 0x59, 0x9a, 0x36, 0xbe, 0x28, 0x5f, 0x6e, 0x95,
	0x9f, 0xc2, 0xfe, 0xfd, 0xea, 0xed, 0x5f, 0x39, 0xfc, 0x12, 0x34, 0x3f, 0x83, 0x61, 0x49, 0x61,
	0x0c, 0x59, 0x29, 0x56, 0x4a, 0x4d, 0xbe, 0x19, 0xb8, 0x1a, 0xf4, 0x44, 0xe9, 0xe7, 0xea, 0x95,
	0x70, 0x0a, 0x50, 0x66, 0x87, 0xc7, 0xb9, 0xe7, 0xd6, 0x6f, 0xf1, 0xbd, 0xf6, 0x22, 0x17, 0xe1,
	0x3b, 0x78, 0x0b, 0x6e, 0x25, 0x0e, 0x34, 0xd0, 0x76, 0x9e, 0xfe, 0xc9, 0x96, 0x4d, 0xc1, 0x72,
	0x05, 0x8e, 0xfd, 0x00, 0x3c, 0xca, 0x81, 0x8d, 0x4c, 0xfc, 0x51, 0x73, 0x6c, 0x8f, 0x97, 0x83,
	0xec, 0xcd, 0x5e, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x3d, 0x6e, 0xba, 0xc7, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	GetPostFeed(ctx context.Context, in *GetPostFeedRequest, opts ...grpc.CallOption) (*GetPostFeedResponse, error)
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostFeed(ctx context.Context, in *GetPostFeedRequest, opts ...grpc.CallOption) (*GetPostFeedResponse, error) {
	out := new(GetPostFeedResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/GetPostFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	out := new(LikePostResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/LikePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	GetPostFeed(context.Context, *GetPostFeedRequest) (*GetPostFeedResponse, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) GetPostFeed(ctx context.Context, req *GetPostFeedRequest) (*GetPostFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostFeed not implemented")
}
func (*UnimplementedPostServiceServer) LikePost(ctx context.Context, req *LikePostRequest) (*LikePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikePost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/GetPostFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostFeed(ctx, req.(*GetPostFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/LikePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "GetPostFeed",
			Handler:    _PostService_GetPostFeed_Handler,
		},
		{
			MethodName: "LikePost",
			Handler:    _PostService_LikePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/post.proto",
}
